# Generated by Django 4.2.1 on 2023-06-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pe', 'Pending'), ('or', 'Ordered')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
