# Generated by Django 4.2.1 on 2023-06-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_tag_products_category_products_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(blank=True, to='home.tag'),
        ),
    ]
